name = "jiwonz/dirs"
version = "0.4.0"
description = "A library for lune that provides config/cache/data paths. Heavily inspired by dirs-rs"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/dirs-lune/"
license = "MIT"
includes = ["src/**", "README.md", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.1" }
greentea = { name = "corecii/greentea", version = "^0.4.10" }

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.8" }
