name = "jiwonz/dirs"
version = "0.1.2"
description = "A library for lune that provides config/cache/data paths. Heavily inspired by dirs-rs"
authors = ["jiwonz"]
repository = "https://github.com/jiwonz/dirs-lune/"
license = "MIT"
includes = ["src", "README.md", "pesde.toml", "LICENSE.md"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.1.0" }
greentea = { name = "corecii/greentea", version = "^0.4.10" }
