name = "jiwonz/dirs"
version = "0.5.1"
description = "A library for lune that provides config/cache/data paths. Heavily inspired by dirs-rs"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/dirs-lune/"
license = "MIT"
includes = ["src/**", "README.md", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.10.0"
pesde = "^0.7.0"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
greentea = { name = "abidbmt/greentea", version = "^0.5.1" }
