name = "jiwonz/dirs"
version = "0.5.1"
description = "A library for lune that provides config/cache/data paths. Heavily inspired by dirs-rs"
authors = ["jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/dirs-lune/"
license = "MIT"
includes = ["src/**", "README.md", "pesde.toml", "LICENSE"]

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[engines]
lune = "^0.10.2"
pesde = "^0.7.1"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
greentea = { name = "jiwonz/greentea_luau", version = "^0.2.0", target = "luau" }
